name: Weekly cron

on:
  schedule:
    # Weekly Monday 6AM build
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
    with:
      envs: |
        - macos: test-py39
          python-version: 3.9
        - macos: test-py310
          python-version: 3.10
        - macos: test-py311
          python-version: 3.11
        - linux: test-devdeps
